### ISSUE TITLE
Does not support environment docker variables

### ISSUE THREAD

**Issue by pomazanbohdan** [blomstra/flarum-redis#14]
My container have env:
REDIS_HOST=flarum-redis

but "Connection refused [tcp://127.0.0.1:6379]"

Use https://github.com/crazy-max/docker-flarum
https://gitlab.xxlab.tech/xxlab/awesome-docker-compose/-/blob/master/flarum/docker-compose.yml?ref_type=heads

https://github.com/glowingblue/flarum-ext-redis-setup/issues/3

**Comment by luceos** [comment]
It's up to you to configure redis. If the default is used then you're not using the extender as per readme. 

Can you point out where you set the redis host if you think the extender is not working?

**Comment by pomazanbohdan** [comment]
I run everything in a docker and I don't have access to the configuration files. 

All connection settings are passed through environment variables

Everything can be found at the links above.

**Comment by luceos** [comment]
I don't remember there being support for environment variables in this package and I do not feel it's absolutely necessary as you can use the flarum config file for that. Feel free to pr the functionality if you like.

Ps I run flarum in docker too and can still edit the config file however I need.

**Comment by pomazanbohdan** [comment]
> Ps I run flarum in docker too and can still edit the config file however I need.

Please provide an example of how you connect the configuration file and an example of its content.

**Comment by luceos** [comment]
You can use the php `getenv()` function inside your config.php. As long as a database exists, this will work without issue.
